[CMake] Require C++14
On 16.04, fix:
…/dynamic-graph-python-4.0.0/include/dynamic-graph/python/module.hh:47:26: error: 'exposeEntity' function uses 'auto' type specifier without trailing return type
inline auto exposeEntity() {
^