16.04
fix:
> include/dynamic-graph/python/dynamic-graph-py.hh::33:25: error: 'stl_input_iterator' is not a member of 'bp'

fix:
> include/dynamic-graph/python/module.hh:47:26: error: 'exposeEntity' function uses 'auto' type specifier without trailing return type

doesn't fix:
> src/dynamic-graph/dynamic-graph-py.cc:191:24: error: 'raw_function' is not a member of 'bp'
as this was added in Boost v1.60, and 16.04 has 1.58