add missing include
On 16.04, fix:
…/dynamic-graph-python-4.0.0/src/dynamic_graph/dynamic-graph-py.cc: In function 'void exposeCommand()':
…/dynamic-graph-python-4.0.0/src/dynamic_graph/dynamic-graph-py.cc:191:24: error: 'raw_function' is not a member of 'bp'
.def("__call__", bp::raw_function(dg::python::entity::executeCmd, 1), "execute the command")
^