add missing include
On 16.04, fix:
…/dynamic-graph-python-4.0.0/include/dynamic-graph/python/dynamic-graph-py.hh:35:25: error: 'stl_input_iterator' is not a member of 'bp'
return std::vector(bp::stl_input_iterator(iterable), bp::stl_input_iterator());
^